image: yosuke/nodebrew
script:
  - nodebrew use stable
  - npm install -g grunt-cli
  - npm install -d
  - npm test
  - nodebrew use latest
  - npm install -g grunt-cli
  - npm install -d
  - npm test
